
export const problems = [
  // Easy
  { id: 1, title: "Two Sum", difficulty: "Easy", href: "https://leetcode.com/problems/two-sum/" },
  { id: 2, title: "Reverse a String", difficulty: "Easy", href: "https://leetcode.com/problems/reverse-string/" },
  { id: 3, title: "Valid Parentheses", difficulty: "Easy", href: "https://leetcode.com/problems/valid-parentheses/" },
  { id: 4, title: "Merge Two Sorted Lists", difficulty: "Easy", href: "https://leetcode.com/problems/merge-two-sorted-lists/" },
  { id: 5, title: "Contains Duplicate", difficulty: "Easy", href: "https://leetcode.com/problems/contains-duplicate/" },
  { id: 17, title: "Valid Anagram", difficulty: "Easy", href: "https://leetcode.com/problems/valid-anagram/" },
  { id: 18, title: "Binary Search", difficulty: "Easy", href: "https://leetcode.com/problems/binary-search/" },
  { id: 19, title: "Invert Binary Tree", difficulty: "Easy", href: "https://leetcode.com/problems/invert-binary-tree/" },
  { id: 20, title: "Maximum Depth of Binary Tree", difficulty: "Easy", href: "https://leetcode.com/problems/maximum-depth-of-binary-tree/" },
  { id: 21, title: "Climbing Stairs", difficulty: "Easy", href: "https://leetcode.com/problems/climbing-stairs/" },
  { id: 31, title: "Palindrome Number", difficulty: "Easy", href: "https://leetcode.com/problems/palindrome-number/" },
  { id: 32, title: "Roman to Integer", difficulty: "Easy", href: "https://leetcode.com/problems/roman-to-integer/" },
  { id: 33, title: "Longest Common Prefix", difficulty: "Easy", href: "https://leetcode.com/problems/longest-common-prefix/" },
  { id: 34, title: "Remove Duplicates from Sorted Array", difficulty: "Easy", href: "https://leetcode.com/problems/remove-duplicates-from-sorted-array/" },
  { id: 35, title: "Remove Element", difficulty: "Easy", href: "https://leetcode.com/problems/remove-element/" },
  { id: 36, title: "Search Insert Position", difficulty: "Easy", href: "https://leetcode.com/problems/search-insert-position/" },
  { id: 37, title: "Plus One", difficulty: "Easy", href: "https://leetcode.com/problems/plus-one/" },
  { id: 38, title: "Sqrt(x)", difficulty: "Easy", href: "https://leetcode.com/problems/sqrtx/" },
  { id: 39, title: "Symmetric Tree", difficulty: "Easy", href: "https://leetcode.com/problems/symmetric-tree/" },
  { id: 40, title: "Best Time to Buy and Sell Stock", difficulty: "Easy", href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/" },
  { id: 41, title: "Single Number", difficulty: "Easy", href: "https://leetcode.com/problems/single-number/" },
  { id: 42, title: "Linked List Cycle", difficulty: "Easy", href: "https://leetcode.com/problems/linked-list-cycle/" },
  { id: 43, title: "Min Stack", difficulty: "Easy", href: "https://leetcode.com/problems/min-stack/" },
  { id: 44, title: "Intersection of Two Linked Lists", difficulty: "Easy", href: "https://leetcode.com/problems/intersection-of-two-linked-lists/" },
  { id: 45, title: "Majority Element", difficulty: "Easy", href: "https://leetcode.com/problems/majority-element/" },
  { id: 46, title: "Reverse Linked List", difficulty: "Easy", href: "https://leetcode.com/problems/reverse-linked-list/" },
  { id: 47, title: "Move Zeroes", difficulty: "Easy", href: "https://leetcode.com/problems/move-zeroes/" },
  { id: 48, title: "Palindrome Linked List", difficulty: "Easy", href: "https://leetcode.com/problems/palindrome-linked-list/" },
  { id: 49, title: "Missing Number", difficulty: "Easy", href: "https://leetcode.com/problems/missing-number/" },
  { id: 50, title: "First Unique Character in a String", difficulty: "Easy", href: "https://leetcode.com/problems/first-unique-character-in-a-string/" },
  { id: 101, title: "Find the Index of the First Occurrence in a String", difficulty: "Easy", href: "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/" },
  { id: 102, title: "Binary Tree Inorder Traversal", difficulty: "Easy", href: "https://leetcode.com/problems/binary-tree-inorder-traversal/" },
  { id: 103, title: "Same Tree", difficulty: "Easy", href: "https://leetcode.com/problems/same-tree/" },
  { id: 104, title: "Convert Sorted Array to Binary Search Tree", difficulty: "Easy", href: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/" },
  { id: 105, title: "Balanced Binary Tree", difficulty: "Easy", href: "https://leetcode.com/problems/balanced-binary-tree/" },
  { id: 115, title: "Path Sum", difficulty: "Easy", href: "https://leetcode.com/problems/path-sum/" },
  { id: 116, title: "Intersection of Two Arrays II", difficulty: "Easy", href: "https://leetcode.com/problems/intersection-of-two-arrays-ii/" },
  { id: 117, title: "Is Subsequence", difficulty: "Easy", href: "https://leetcode.com/problems/is-subsequence/" },
  { id: 118, title: "Range Sum Query - Immutable", difficulty: "Easy", href: "https://leetcode.com/problems/range-sum-query-immutable/" },
  { id: 119, title: "Middle of the Linked List", difficulty: "Easy", href: "https://leetcode.com/problems/middle-of-the-linked-list/" },
  { id: 120, title: "Reverse Vowels of a String", difficulty: "Easy", href: "https://leetcode.com/problems/reverse-vowels-of-a-string/" },
  { id: 121, title: "Valid Palindrome", difficulty: "Easy", href: "https://leetcode.com/problems/valid-palindrome/" },
  { id: 122, title: "Binary Tree Paths", difficulty: "Easy", href: "https://leetcode.com/problems/binary-tree-paths/" },
  { id: 123, title: "Lowest Common Ancestor of a Binary Search Tree", difficulty: "Easy", href: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/" },
  { id: 124, title: "Backspace String Compare", difficulty: "Easy", href: "https://leetcode.com/problems/backspace-string-compare/" },
  { id: 125, title: "Diameter of Binary Tree", difficulty: "Easy", href: "https://leetcode.com/problems/diameter-of-binary-tree/" },
  { id: 147, title: "Maximum Subarray", difficulty: "Easy", href: "https://leetcode.com/problems/maximum-subarray/" },
  { id: 148, title: "Length of Last Word", difficulty: "Easy", href: "https://leetcode.com/problems/length-of-last-word/" },
  { id: 149, title: "Merge Sorted Array", difficulty: "Easy", href: "https://leetcode.com/problems/merge-sorted-array/" },
  { id: 150, title: "Pascal's Triangle", difficulty: "Easy", href: "https://leetcode.com/problems/pascals-triangle/" },
  { id: 151, title: "Valid Palindrome II", difficulty: "Easy", href: "https://leetcode.com/problems/valid-palindrome-ii/" },
  { id: 152, title: "Merge Two Binary Trees", difficulty: "Easy", href: "https://leetcode.com/problems/merge-two-binary-trees/" },
  { id: 153, title: "Subtree of Another Tree", difficulty: "Easy", href: "https://leetcode.com/problems/subtree-of-another-tree/" },
  { id: 154, title: "Ransom Note", difficulty: "Easy", href: "https://leetcode.com/problems/ransom-note/" },
  { id: 155, title: "First Bad Version", difficulty: "Easy", href: "https://leetcode.com/problems/first-bad-version/" },
  { id: 156, title: "Summary Ranges", difficulty: "Easy", href: "https://leetcode.com/problems/summary-ranges/" },
  { id: 157, title: "Happy Number", difficulty: "Easy", href: "https://leetcode.com/problems/happy-number/" },
  { id: 158, title: "Reverse Bits", difficulty: "Easy", href: "https://leetcode.com/problems/reverse-bits/" },
  { id: 159, title: "Fizz Buzz", difficulty: "Easy", href: "https://leetcode.com/problems/fizz-buzz/" },
  { id: 160, title: "Power of Two", difficulty: "Easy", href: "https://leetcode.com/problems/power-of-two/" },
  { id: 161, title: "Power of Three", difficulty: "Easy", href: "https://leetcode.com/problems/power-of-three/" },
  { id: 162, title: "Power of Four", difficulty: "Easy", href: "https://leetcode.com/problems/power-of-four/" },
  { id: 163, title: "Counting Bits", difficulty: "Easy", href: "https://leetcode.com/problems/counting-bits/" },
  { id: 164, title: "Two Sum II - Input Array Is Sorted", difficulty: "Easy", href: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/" },
  { id: 165, title: "Find All Numbers Disappeared in an Array", difficulty: "Easy", href: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/" },
  { id: 166, title: "Implement Stack using Queues", difficulty: "Easy", href: "https://leetcode.com/problems/implement-stack-using-queues/" },

  // Medium
  { id: 6, title: "Add Two Numbers", difficulty: "Medium", href: "https://leetcode.com/problems/add-two-numbers/" },
  { id: 7, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", href: "https://leetcode.com/problems/longest-substring-without-repeating-characters/" },
  { id: 8, title: "Container With Most Water", difficulty: "Medium", href: "https://leetcode.com/problems/container-with-most-water/" },
  { id: 9, title: "Top K Frequent Elements", difficulty: "Medium", href: "https://leetcode.com/problems/top-k-frequent-elements/" },
  { id: 10, title: "Product of Array Except Self", difficulty: "Medium", href: "https://leetcode.com/problems/product-of-array-except-self/" },
  { id: 11, title: "Coin Change", difficulty: "Medium", href: "https://leetcode.com/problems/coin-change/" },
  { id: 22, title: "Group Anagrams", difficulty: "Medium", href: "https://leetcode.com/problems/group-anagrams/" },
  { id: 23, title: "Validate Binary Search Tree", difficulty: "Medium", href: "https://leetcode.com/problems/validate-binary-search-tree/" },
  { id: 24, title: "Kth Smallest Element in a BST", difficulty: "Medium", href: "https://leetcode.com/problems/kth-smallest-element-in-a-bst/" },
  { id: 25, title: "Longest Increasing Subsequence", difficulty: "Medium", href: "https://leetcode.com/problems/longest-increasing-subsequence/" },
  { id: 26, title: "Course Schedule", difficulty: "Medium", href: "https://leetcode.com/problems/course-schedule/" },
  { id: 27, title: "Number of Islands", difficulty: "Medium", href: "https://leetcode.com/problems/number-of-islands/" },
  { id: 51, title: "String to Integer (atoi)", difficulty: "Medium", href: "https://leetcode.com/problems/string-to-integer-atoi/" },
  { id: 52, title: "3Sum", difficulty: "Medium", href: "https://leetcode.com/problems/3sum/" },
  { id: 53, title: "Remove Nth Node From End of List", difficulty: "Medium", href: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/" },
  { id: 54, title: "Generate Parentheses", difficulty: "Medium", href: "https://leetcode.com/problems/generate-parentheses/" },
  { id: 55, title: "Rotate Image", difficulty: "Medium", href: "https://leetcode.com/problems/rotate-image/" },
  { id: 56, title: "Jump Game", difficulty: "Medium", href: "https://leetcode.com/problems/jump-game/" },
  { id: 57, title: "Merge Intervals", difficulty: "Medium", href: "https://leetcode.com/problems/merge-intervals/" },
  { id: 58, title: "Unique Paths", difficulty: "Medium", href: "https://leetcode.com/problems/unique-paths/" },
  { id: 59, title: "Set Matrix Zeroes", difficulty: "Medium", href: "https://leetcode.com/problems/set-matrix-zeroes/" },
  { id: 60, title: "Sort Colors", difficulty: "Medium", href: "https://leetcode.com/problems/sort-colors/" },
  { id: 61, title: "Word Search", difficulty: "Medium", href: "https://leetcode.com/problems/word-search/" },
  { id: 62, title: "Subsets", difficulty: "Medium", href: "https://leetcode.com/problems/subsets/" },
  { id: 63, title: "Binary Tree Level Order Traversal", difficulty: "Medium", href: "https://leetcode.com/problems/binary-tree-level-order-traversal/" },
  { id: 64, title: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "Medium", href: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/" },
  { id: 65, title: "Clone Graph", difficulty: "Medium", href: "https://leetcode.com/problems/clone-graph/" },
  { id: 66, title: "Gas Station", difficulty: "Medium", href: "https://leetcode.com/problems/gas-station/" },
  { id: 67, title: "LRU Cache", difficulty: "Medium", href: "https://leetcode.com/problems/lru-cache/" },
  { id: 68, title: "Find the Duplicate Number", difficulty: "Medium", href: "https://leetcode.com/problems/find-the-duplicate-number/" },
  { id: 69, title: "House Robber", difficulty: "Medium", href: "https://leetcode.com/problems/house-robber/" },
  { id: 70, title: "Kth Largest Element in an Array", difficulty: "Medium", href: "https://leetcode.com/problems/kth-largest-element-in-an-array/" },
  { id: 106, title: "Longest Palindromic Substring", difficulty: "Medium", href: "https://leetcode.com/problems/longest-palindromic-substring/" },
  { id: 107, title: "Permutations", difficulty: "Medium", href: "https://leetcode.com/problems/permutations/" },
  { id: 108, title: "Combination Sum", difficulty: "Medium", href: "https://leetcode.com/problems/combination-sum/" },
  { id: 109, title: "Search in Rotated Sorted Array", difficulty: "Medium", href: "https://leetcode.com/problems/search-in-rotated-sorted-array/" },
  { id: 126, title: "Letter Combinations of a Phone Number", difficulty: "Medium", href: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/" },
  { id: 127, title: "Spiral Matrix", difficulty: "Medium", href: "https://leetcode.com/problems/spiral-matrix/" },
  { id: 128, title: "Rotate List", difficulty: "Medium", href: "https://leetcode.com/problems/rotate-list/" },
  { id: 129, title: "Search a 2D Matrix", difficulty: "Medium", href: "https://leetcode.com/problems/search-a-2d-matrix/" },
  { id: 130, title: "Binary Tree Zigzag Level Order Traversal", difficulty: "Medium", href: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/" },
  { id: 131, title: "Word Break", difficulty: "Medium", href: "https://leetcode.com/problems/word-break/" },
  { id: 132, title: "Reorder List", difficulty: "Medium", href: "https://leetcode.com/problems/reorder-list/" },
  { id: 133, title: "Maximum Product Subarray", difficulty: "Medium", href: "https://leetcode.com/problems/maximum-product-subarray/" },
  { id: 134, title: "Find Peak Element", difficulty: "Medium", href: "https://leetcode.com/problems/find-peak-element/" },
  { id: 135, title: "Daily Temperatures", difficulty: "Medium", href: "https://leetcode.com/problems/daily-temperatures/" },
  { id: 167, title: "3Sum Closest", difficulty: "Medium", href: "https://leetcode.com/problems/3sum-closest/" },
  { id: 168, title: "Combination Sum II", difficulty: "Medium", href: "https://leetcode.com/problems/combination-sum-ii/" },
  { id: 169, title: "Permutations II", difficulty: "Medium", href: "https://leetcode.com/problems/permutations-ii/" },
  { id: 170, title: "Pow(x, n)", difficulty: "Medium", href: "https://leetcode.com/problems/powx-n/" },
  { id: 171, title: "Subsets II", difficulty: "Medium", href: "https://leetcode.com/problems/subsets-ii/" },
  { id: 172, title: "Decode Ways", difficulty: "Medium", href: "https://leetcode.com/problems/decode-ways/" },
  { id: 173, title: "Reverse Linked List II", difficulty: "Medium", href: "https://leetcode.com/problems/reverse-linked-list-ii/" },
  { id: 174, title: "Binary Tree Right Side View", difficulty: "Medium", href: "https://leetcode.com/problems/binary-tree-right-side-view/" },
  { id: 175, title: "Longest Repeating Character Replacement", difficulty: "Medium", href: "https://leetcode.com/problems/longest-repeating-character-replacement/" },
  { id: 176, title: "Palindromic Substrings", difficulty: "Medium", href: "https://leetcode.com/problems/palindromic-substrings/" },
  { id: 177, title: "House Robber II", difficulty: "Medium", href: "https://leetcode.com/problems/house-robber-ii/" },
  { id: 178, title: "Partition Labels", difficulty: "Medium", href: "https://leetcode.com/problems/partition-labels/" },
  { id: 179, title: "Sort List", difficulty: "Medium", href: "https://leetcode.com/problems/sort-list/" },
  { id: 180, title: "Evaluate Reverse Polish Notation", difficulty: "Medium", href: "https://leetcode.com/problems/evaluate-reverse-polish-notation/" },
  { id: 181, title: "Find Minimum in Rotated Sorted Array", difficulty: "Medium", href: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/" },
  { id: 182, title: "Course Schedule II", difficulty: "Medium", href: "https://leetcode.com/problems/course-schedule-ii/" },
  { id: 183, title: "Non-overlapping Intervals", difficulty: "Medium", href: "https://leetcode.com/problems/non-overlapping-intervals/" },
  { id: 184, title: "Find All Anagrams in a String", difficulty: "Medium", href: "https://leetcode.com/problems/find-all-anagrams-in-a-string/" },
  { id: 185, title: "Meeting Rooms II", difficulty: "Medium", href: "https://leetcode.com/problems/meeting-rooms-ii/" },
  { id: 186, title: "Path Sum III", difficulty: "Medium", href: "https://leetcode.com/problems/path-sum-iii/" },

  // Hard
  { id: 12, title: "Median of Two Sorted Arrays", difficulty: "Hard", href: "https://leetcode.com/problems/median-of-two-sorted-arrays/" },
  { id: 13, title: "Trapping Rain Water", difficulty: "Hard", href: "https://leetcode.com/problems/trapping-rain-water/" },
  { id: 14, title: "Merge k Sorted Lists", difficulty: "Hard", href: "https://leetcode.com/problems/merge-k-sorted-lists/" },
  { id: 15, title: "Largest Rectangle in Histogram", difficulty: "Hard", href: "https://leetcode.com/problems/largest-rectangle-in-histogram/" },
  { id: 16, title: "Sliding Window Maximum", difficulty: "Hard", href: "https://leetcode.com/problems/sliding-window-maximum/" },
  { id: 28, title: "Regular Expression Matching", difficulty: "Hard", href: "https://leetcode.com/problems/regular-expression-matching/" },
  { id: 29, title: "Word Ladder", difficulty: "Hard", href: "https://leetcode.com/problems/word-ladder/" },
  { id: 30, title: "N-Queens", difficulty: "Hard", href: "https://leetcode.com/problems/n-queens/" },
  { id: 71, title: "Text Justification", difficulty: "Hard", href: "https://leetcode.com/problems/text-justification/" },
  { id: 72, title: "Minimum Window Substring", difficulty: "Hard", href: "https://leetcode.com/problems/minimum-window-substring/" },
  { id: 73, title: "Binary Tree Maximum Path Sum", difficulty: "Hard", href: "https://leetcode.com/problems/binary-tree-maximum-path-sum/" },
  { id: 74, title: "Max Points on a Line", difficulty: "Hard", href: "https://leetcode.com/problems/max-points-on-a-line/" },
  { id: 75, title: "Word Break II", difficulty: "Hard", href: "https://leetcode.com/problems/word-break-ii/" },
  { id: 76, title: "Find Median from Data Stream", difficulty: "Hard", href: "https://leetcode.com/problems/find-median-from-data-stream/" },
  { id: 77, title: "Burst Balloons", difficulty: "Hard", href: "https://leetcode.com/problems/burst-balloons/" },
  { id: 78, title: "Longest Consecutive Sequence", difficulty: "Hard", href: "https://leetcode.com/problems/longest-consecutive-sequence/" },
  { id: 79, title: "Wildcard Matching", difficulty: "Hard", href: "https://leetcode.com/problems/wildcard-matching/" },
  { id: 80, title: "Best Time to Buy and Sell Stock III", difficulty: "Hard", href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/" },
  { id: 110, title: "First Missing Positive", difficulty: "Hard", href: "https://leetcode.com/problems/first-missing-positive/" },
  { id: 111, title: "Sudoku Solver", difficulty: "Hard", href: "https://leetcode.com/problems/sudoku-solver/" },
  { id: 112, title: "Edit Distance", difficulty: "Hard", href: "https://leetcode.com/problems/edit-distance/" },
  { id: 113, title: "Maximal Rectangle", difficulty: "Hard", href: "https://leetcode.com/problems/maximal-rectangle/" },
  { id: 114, title: "Serialize and Deserialize Binary Tree", difficulty: "Hard", href: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/" },
  { id: 136, title: "Reverse Nodes in k-Group", difficulty: "Hard", href: "https://leetcode.com/problems/reverse-nodes-in-k-group/" },
  { id: 137, title: "Candy", difficulty: "Hard", href: "https://leetcode.com/problems/candy/" },
  { id: 138, title: "Basic Calculator", difficulty: "Hard", href: "https://leetcode.com/problems/basic-calculator/" },
  { id: 139, title: "Word Search II", difficulty: "Hard", href: "https://leetcode.com/problems/word-search-ii/" },
  { id: 140, title: "Number of Islands II", difficulty: "Hard", href: "https://leetcode.com/problems/number-of-islands-ii/" },
  { id: 141, title: "Critical Connections in a Network", difficulty: "Hard", href: "https://leetcode.com/problems/critical-connections-in-a-network/" },
  { id: 142, title: "Maximum Frequency Stack", difficulty: "Hard", href: "https://leetcode.com/problems/maximum-frequency-stack/" },
  { id: 143, title: "Robot Room Cleaner", difficulty: "Hard", href: "https://leetcode.com/problems/robot-room-cleaner/" },
  { id: 144, title: "Find K-th Smallest Pair Distance", difficulty: "Hard", href: "https://leetcode.com/problems/find-k-th-smallest-pair-distance/" },
  { id: 145, title: "Best Time to Buy and Sell Stock IV", difficulty: "Hard", href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/" },
  { id: 146, title: "Palindrome Pairs", difficulty: "Hard", href: "https://leetcode.com/problems/palindrome-pairs/" },
  { id: 187, title: "Longest Valid Parentheses", difficulty: "Hard", href: "https://leetcode.com/problems/longest-valid-parentheses/" },
  { id: 188, title: "Substring with Concatenation of All Words", difficulty: "Hard", href: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/" },
  { id: 189, title: "Jump Game II", difficulty: "Hard", href: "https://leetcode.com/problems/jump-game-ii/" },
  { id: 190, title: "N-Queens II", difficulty: "Hard", href: "https://leetcode.com/problems/n-queens-ii/" },
  { id: 191, title: "Word Ladder II", difficulty: "Hard", href: "https://leetcode.com/problems/word-ladder-ii/" },
  { id: 192, title: "Find Minimum in Rotated Sorted Array II", difficulty: "Hard", href: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii/" },
  { id: 193, title: "Alien Dictionary", difficulty: "Hard", href: "https://leetcode.com/problems/alien-dictionary/" },
  { id: 194, title: "Integer to English Words", difficulty: "Hard", href: "https://leetcode.com/problems/integer-to-english-words/" },
  { id: 195, title: "Best Time to Buy and Sell Stock with Cooldown", difficulty: "Hard", href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/" },
  { id: 196, title: "Best Time to Buy and Sell Stock with Transaction Fee", difficulty: "Hard", href: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/" },
  { id: 197, title: "Redundant Connection II", difficulty: "Hard", href: "https://leetcode.com/problems/redundant-connection-ii/" },
  { id: 198, title: "Race Car", difficulty: "Hard", href: "https://leetcode.com/problems/race-car/" },
  { id: 199, title: "Reaching Points", difficulty: "Hard", href: "https://leetcode.com/problems/reaching-points/" },
  { id: 200, title: "Swim in Rising Water", difficulty: "Hard", href: "https://leetcode.com/problems/swim-in-rising-water/" },
  { id: 201, title: "Chalkboard XOR Game", difficulty: "Hard", href: "https://leetcode.com/problems/chalkboard-xor-game/" },
  { id: 202, title: "Shortest Path Visiting All Nodes", difficulty: "Hard", href: "https://leetcode.com/problems/shortest-path-visiting-all-nodes/" },
  { id: 203, title: "Smallest Range Covering Elements from K Lists", difficulty: "Hard", href: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/" },
  { id: 204, title: "Binary Tree Cameras", difficulty: "Hard", href: "https://leetcode.com/problems/binary-tree-cameras/" },
  { id: 205, title: "Russian Doll Envelopes", difficulty: "Hard", href: "https://leetcode.com/problems/russian-doll-envelopes/" },
  { id: 206, title: "Maximum Profit in Job Scheduling", difficulty: "Hard", href: "https://leetcode.com/problems/maximum-profit-in-job-scheduling/" },
  { id: 207, title: "Frog Jump", difficulty: "Hard", href: "https://leetcode.com/problems/frog-jump/" },
  { id: 208, title: "Number of Atoms", difficulty: "Hard", href: "https://leetcode.com/problems/number-of-atoms/" },
  { id: 209, title: "Making A Large Island", difficulty: "Hard", href: "https://leetcode.com/problems/making-a-large-island/" },
  { id: 210, title: "Remove Invalid Parentheses", difficulty: "Hard", href: "https://leetcode.com/problems/remove-invalid-parentheses/" },
  { id: 211, title: "Count of Smaller Numbers After Self", difficulty: "Hard", href: "https://leetcode.com/problems/count-of-smaller-numbers-after-self/" },
  { id: 212, title: "Concatenated Words", difficulty: "Hard", href: "https://leetcode.com/problems/concatenated-words/" },
  { id: 213, title: "Distinct Subsequences", difficulty: "Hard", href: "https://leetcode.com/problems/distinct-subsequences/" },
  { id: 214, title: "Scramble String", difficulty: "Hard", href: "https://leetcode.com/problems/scramble-string/" },
  { id: 215, title: "Interleaving String", difficulty: "Hard", href: "https://leetcode.com/problems/interleaving-string/" },
  { id: 216, title: "Number of Ways to Form a Target String Given a Dictionary", difficulty: "Hard", href: "https://leetcode.com/problems/number-of-ways-to-form-a-target-string-given-a-dictionary/" },
];

    
    